name: Deploy Function App

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group to deploy into (optional, falls back to SECRET AZURE_RESOURCE_GROUP)'
        required: false
      function_app_name:
        description: 'Function App name (optional, falls back to SECRET AZURE_FUNCTIONAPP_NAME)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Azure Login (OIDC)'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Determine deployment targets
        id: vars
        env:
          RG: ${{ github.event.inputs.resource_group || secrets.AZURE_RESOURCE_GROUP }}
          FUNC: ${{ github.event.inputs.function_app_name || secrets.AZURE_FUNCTIONAPP_NAME }}
        run: |
          echo "resource_group=$RG" >> $GITHUB_OUTPUT
          echo "function_app_name=$FUNC" >> $GITHUB_OUTPUT

      - name: Zip function app
        run: |
          cd functionApp
          zip -r ../functionapp.zip .

      - name: Deploy function app (zip)
        env:
          AZURE_RESOURCE_GROUP: ${{ steps.vars.outputs.resource_group }}
          AZURE_FUNCTIONAPP_NAME: ${{ steps.vars.outputs.function_app_name }}
        run: |
          az functionapp deployment source config-zip --name "$AZURE_FUNCTIONAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" --src functionapp.zip
